//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Comite
    {
        public int id { get; set; }
        public Nullable<int> id_finance { get; set; }
        public string etat { get; set; }
        public Nullable<System.DateTime> date_comite { get; set; }
        [Required]
        [DisplayName("Type du Comité")]
        public string type_comite { get; set; }
        public Nullable<long> id_folder { get; set; }
        public string statut { get; set; }
    
        public virtual financial_data financial_data { get; set; }
        public virtual folder folder { get; set; }
    }
}
