//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class financial_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public financial_data()
        {
            this.Comite = new HashSet<Comite>();
        }
    
        public int id { get; set; }
        [Required]
        [DisplayName("Valeur vénale libre")]
        public Nullable<double> vvl { get; set; }
        public Nullable<double> prix_m { get; set; }
        [Required]
        [DisplayName("Valeur vénale occupé")]

        public Nullable<double> vvo { get; set; }
        [Required]
        [DisplayName("Valeur financiére")]
        public Nullable<double> vf { get; set; }
         [Required]
        [DisplayName("Décote d'occupation")]
        public Nullable<double> decote_occupation { get; set; }
        [Required]
        [DisplayName("Décote totale financiére")]
        public Nullable<double> decote_totale { get; set; }
        [Required]
        [DisplayName("Bouquet")]
        public Nullable<double> bouquet { get; set; }
        [Required]
        [DisplayName("Bouquet /VVL")]
        public Nullable<double> bouquet_vvl { get; set; }
        public Nullable<int> propriete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comite> Comite { get; set; }
        public virtual Propriete Propriete1 { get; set; }
    }
}
