//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class folder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public folder()
        {
            this.Comite = new HashSet<Comite>();
            this.Propriete = new HashSet<Propriete>();
            this.tiers = new HashSet<tiers>();
        }
    
        public long id { get; set; }
        [Required]
        [DisplayName("Apporteur ")]
        public string contributor { get; set; }
        [Required]
        [DisplayName("Code Dossier")]
        public string folder_code { get; set; }
        [DisplayName("Date de Création")]
        public Nullable<System.DateTime> created_at { get; set; }
        [DisplayName("Créer finparanciére")]
        public string created_by { get; set; }
        [DisplayName("Etat ")]
        public string state { get; set; }
        public Nullable<int> version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comite> Comite { get; set; }
        public virtual version version1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propriete> Propriete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tiers> tiers { get; set; }
    }
}
