//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionImmobilierEntities : DbContext
    {
        public GestionImmobilierEntities()
            : base("name=GestionImmobilierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<affectation> affectation { get; set; }
        public virtual DbSet<Comite> Comite { get; set; }
        public virtual DbSet<financial_data> financial_data { get; set; }
        public virtual DbSet<folder> folder { get; set; }
        public virtual DbSet<fonds> fonds { get; set; }
        public virtual DbSet<Lots> Lots { get; set; }
        public virtual DbSet<Propriete> Propriete { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<table_> table_ { get; set; }
        public virtual DbSet<tiers> tiers { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<version> version { get; set; }
        public virtual DbSet<version1> version1 { get; set; }
    }
}
