//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Propriete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propriete()
        {
            this.affectation = new HashSet<affectation>();
            this.financial_data = new HashSet<financial_data>();
            this.Lots = new HashSet<Lots>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        [Required]
        [DisplayName("Région ")]
        public string region { get; set; }
        [Required]
        [DisplayName("Ville")]
        public string city { get; set; }
        [Required]
        [DisplayName("Adresse1 ")]
        public string add1 { get; set; }
        [Required]
        [DisplayName("Adresse2")]
        public string add2 { get; set; }
        [Required]
        [DisplayName("Adresse3 ")]
        public string add3 { get; set; }
        [Required]
        [DisplayName("Code postale")]
        public Nullable<int> zip_Code { get; set; }
        [Required]
        [DisplayName("Bien")]
        public string bien { get; set; }
        [DisplayName("Surface ")]
        public Nullable<double> area { get; set; }
        [DisplayName("Type Bien")]
        public Nullable<int> type { get; set; }
        public Nullable<long> id_folder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affectation> affectation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<financial_data> financial_data { get; set; }
        public virtual folder folder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lots> Lots { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
