//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int id { get; set; }
        [Required]
        [DisplayName("Prenom ")]
        public string firstname { get; set; }
        [Required]
        [DisplayName("Nom")]
        public string lastname { get; set; }
        [Required]
        [DisplayName("Mot de passe ")]
        public string password { get; set; }
        public Nullable<int> age { get; set; }
        [Required]
        [DisplayName("E-mail ")]
        public string email { get; set; }
        public Nullable<int> role { get; set; }
    
        public virtual Role Role1 { get; set; }
    }
}
