//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class version1
    {
        public string Cible { get; set; }
        public Nullable<double> HOMME___âge { get; set; }
        public Nullable<double> FEMME___âge { get; set; }
        public Nullable<double> Espérance { get; set; }
        public Nullable<double> tx_rente { get; set; }
        public Nullable<double> dt_us_ { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public Nullable<double> F14 { get; set; }
        public int id { get; set; }
    }
}
